src/datascript/pull_api.cljs, test/datascript/test/pull_api.cljs
This patch reorders the `cond` in `pull-attr-datoms` to allow map specs to override the default behaviour of recursively expanding component entities.
=> Support overriding default expansion of component entities

src/datascript/pull_api.cljs, test/datascript/test/pull_api.cljs
This PR provides similar behaviour to recursion specs (i.e. only returns a map containing `:db/id` for entities which have already been seen along a given path). I have to be honest, though, and say that I'm not convinced allowing loops on component attributes is the right way to go; `:db/isComponent` currently allows one to explicitly constrain parts of the schema more strictly than just `:db/ref` - in the pull API this is used to, for example, make the assumption that navigating a _reverse_ component relationship will yield precisely 0 or 1 results depending on whether the attribute exists on the given entity.
It also seems to violate the principle of least surprise (although granted, the original issue that caused this was clearly surprising, but it was caused by a separate issue) - To …
=> First pass at fix for #58

src/datascript/impl/entity.cljc
primary change is that both CLJ and CLJS use `volatile!`s instead of deftype `:mutable`-ish things to manage `touched` and `cache` fields. other changes accommodate common code tactics, with varying degrees of grace.
=> update entity code to function in CLJ

src/datascript/pull_api.cljc, test/datascript/test/pull_api.cljc
Hello.
With the pull api, if you reverse lookup a cardinality-one, non-component attribute inside a map spec, it only yields a single result, but it should yield a collection instead.
Here’s a test snippet to try to clarify. On the current `master` the top two tests will pass, but the bottom two tests (with map specs) will fail.
```clojure
(def test-schema {:father { :db/valueType :db.type/ref }})
(def test-datoms
(->>
[[1 :name  "Petr"]
[2 :name  "David"]
[3 :name  "Thomas"]
[6 :name  "Matthew"]
[2 :father 1]
[3 :father 1]
[6 :father 3]]
(map #(apply d/datom %))))
(def test-db (d/init-db test-datoms test-schema))
(deftest test-pull-reverse-attr-spec
(testing "Reverse non-component references yield collections"
;; Currently these two will pass
(is (= {:name "Thomas" :_father [{:db/id 6}]} …
```
=> Pull API map spec non-component reversed attributes should return collections

test/datascript/test/entity.cljc
[humane-test-output](https://github.com/pjstadig/humane-test-output) plugin caught a common paren oversight when I tried to run the tests locally.
=> Fix sneaky parens caught by humane-test-output

src/datascript/impl/entity.cljc, test/datascript/test/entity.cljc
Using `contains?` on an entity on the JVM caused a null pointer exception because `contains?` expects the `containsKey` method to return a boolean.
I've updated the implementation of Entity to do the right thing on the JVM just like what's done on the cljs implementation (using the not-found arity of key lookup).
=> Fix null pointer exception when `contains?` is called with an entity.

src/datascript/db.cljc, test/datascript/test/transact.cljc
Fixes #126 by not validating old-value (letting it be nil).
=> Let old-value for db.fn/cas be nil

src/datascript/js.cljs, test/js/tests.js
Keywordize attributes in schema->clj looks like a bug(because in other functions you avoid convert user string to keyword). See: https://github.com/tonsky/datascript/issues/153#issuecomment-200723583.
=> Avoid keywordize attributes in schema->clj(closes #153)

src/datascript/query.cljc, test/datascript/test/query_fns.cljc
This commit adds a reader conditional to enable the use of
namespace-qualified symbols as query functions or predicates, when in
JVM Clojure. This allows queries using functions or predicates to be
reused between Datomic and DataScript when running on the JVM.
The semantics of a DataScript query are otherwise unchanged; global var
resolution is only attempted as a final step before failure.
The semantics when operating in a ClojureScript context are entirely
unchanged, since global symbol->var resolution is not supported.
=> Var resolution for query fns/preds when in JVM

src/datascript/query.cljc, test/datascript/test/query_fns.cljc
I'm missing `vector` and `hash-map` as built in functions. I find them useful to construct new data structures that could be transacted, usually in combination with rules. The tests are meant to give a hint of how this could be useful.
=> Built in vector, hash-map

src/datascript/impl/entity.cljc, test/datascript/test/core.cljc, test/datascript/test/entity.cljc
I discovered this with some debugging code like this:
```clojure
(prn (into {} ev) (:event/ok? ev))
```
And it was printing something like:
```clojure
{:event/ok? false} nil
```
Confusingly, if I omitted that debug print statement, `(:event/ok? ev)` returned false. Subsequent calls, however, returned `nil`.
The first commit in this PR isolates the problem to incorrect logical-false handling in the entity value cache. The second commit fixes it.
=> False in cached entity values

src/datascript/db.cljc
(require '[datascript.core :as ds])
(db/index-range (ds/empty-db) ::foo 0 0)
=>
Unhandled java.lang.ClassCastException
java.lang.String cannot be cast to clojure.lang.IPersistentMap
core.clj: 4725  clojure.core/ex-info
core.clj: 4725  clojure.core/ex-info
db.cljc:  394  datascript.db.DB/_index_range
core.cljc:  106  datascript.core$index_range/invokeStatic
core.cljc:  104  datascript.core$index_range/invoke
db.cljc:  237  onair.db$index_range/invokeStatic
db.cljc:  235  onair.db$index_range/invoke
=> index-range on unindexed attr throws ClassCastException instead of assertion with actual cause

src/datascript/core.cljc
Think I found a typo. Is this what you meant?
Also, thanks a lot for datascript. Having a high-quality database that can be deployed alongside the application is super-sweet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tonsky/datascript/299)
=> Fix typo in listen! docs

dev/user.clj
The cljs.closure/Compilable protocol has two methods and right now
running `(node-repl)` from the user ns throws an error about the
missing method `find-sources`
=> Update cljs build settings

src/datascript/lru.cljc
no longer pased on transients. And even if it were calling persistent
on a transient in a side-effecting operation that changes the
transient.
This error would manifest itself just by calling the lru function:
```cljs
(require '[datascript.lru :as lru])
(lru/lru 3)
**error no protocol method -persistent!
```
=> Remove call to `persistent!` in cljs lru print function

src/datascript/query.cljc, test/datascript/test/query.cljc
Clojure can resolve functions from clojure/string so that you can
check for substrings
`[(clojure.string/includes? ?term "X")]`
Clojurescript lacks this runtime resolution so there is no way to
check for string containment. There are some helpful regex functions
but this requires the regex pattern to be constructed outside of the
query. This change allows to create the pattern in the query as
demonstrated in the test:
``` clojure
(d/q '[:find  ?name
:in    [?name ...] ?key
:where [(re-pattern ?key) ?pattern]
[(re-find ?pattern ?name)]]
#{"abc" "abcX" "aXb"}
"X")
```
=> Add `re-pattern` to builtins

src/datascript/core.cljc, src/datascript/db.cljc, src/datascript/pprint.clj
This would enable user to require namespaces behind `core` directly to eliminate startup time cost of requiring `clojure.pprint`
=> extract pprinting to separate ns

src/datascript/pull_parser.cljc, test/datascript/test/pull_parser.cljc
e.g. `(d/pull ?e [{[:foo :as :bar] [:quux]}])`
=> Allow aliasing map keys in pull entry

src/datascript/core.cljc, src/datascript/db.cljc, test/datascript/test/transact.cljc
- :db/retract with null value is treated as :db.fn/retractAttribute
- Docstring for 'transact!' is modified to reflect the change
=> Issue 339: Support: db/retract without value

src/datascript/query.cljc
Fixes following issue:
```clojure
(let [db (d/db-with (d/empty-db) [{:things #{"x" "y" "z"}}
{:things #{}}])]
(d/q '[:find (count ?e) .
:where
[?e :things ?t]
[(empty? ?t)]]
db))
; Expected: 1
; Actual: 2
```
I don't think there's any value in adding a test case just for this?
Cheers.
=> Fix `empty?` builtin

src/datascript/db.cljc, test/datascript/test/tuples.cljc
Allow specifying composite tuple with :db/valueType :db.type/tuple
This schema attribute is optional, but when specified will check that
:db/tupleAttrs is also provided.
This fixes #407
=> Allow :db/valueType :db.type/tuple

src/datascript/pull_api.cljc, test/datascript/test/pull_api.cljc
A wildcard pull on a non-matching ref returns "garbage" attributes:
(d/pull test-db '[*] [:name "No such name"])
=> {:db/id nil, :aka ["Devil" "Tupen"], :child [{:db/id 2} {:db/id 3}], :name "Petr", :father {:db/id 1}, :part [{:db/id 11, :name "Part A.A", :part [{:db/id 12, :name "Part A.A.A", :part [{:db/id 13, :name "Part A.A.A.A"} {:db/id 14, :name "Part A.A.A.B"}]}]} {:db/id 15, :name "Part A.B", :part [{:db/id 16, :name "Part A.B.A", :part [{:db/id 17, :name "Part A.B.A.A"} {:db/id 18, :name "Part A.B.A.B"}]}]} {:db/id 12, :name "Part A.A.A", :part [{:db/id 13, :name "Part A.A.A.A"} {:db/id 14, :name "Part A.A.A.B"}]} {:db/id 13, :name "Part A.A.A.A"} {:db/id 14, :name "Part A.A.A.B"} {:db/id 16, :name "Part A.B.A", :part [{:db/id 17, :name "Part A.B.A.A"} {:db/id 18, :name "Part …
=> Fix broken wildcard pull on non-matching ref

src/datascript/parser.cljc, test/datascript/test/parser_where.cljc
Closes #416. 
This PR allows using symbols(not starting with `?`) as constants in data patterns. This is consistent with Datomic's behaviour. 
Notes:
- I changed the order of parsers in `parse-fn-arg` otherwise `$x` would parse as a constant, and it shouldn't for function arguments.
- I believe the unit test saying `(friends something)` should throw is wrong. I've changed it to a positive test where `something` parses as a constant argument instead.
=> Allow symbols as constants

src/datascript/parser.cljc
Currently `flatten-rule-vars` will only return the free variable symbols if there are required variables. This is due to a misplaced `)`. This is not a big issue as `flatten-rule-vars` is only called in to generate an error message in rule arity validation.
=> Render all variables in rule arity error message

src/datascript/built_ins.cljc, test/datascript/test/query.cljc
Hi again! Would you be open to adding `get` to the builtins? It's the only thing keeping us @logseq from getting off of our datascript fork. I'm aware we could pass `get` as [an input](https://github.com/tonsky/datascript/issues/360) but are needs are a bit complex as our users already rely on this builtin to writing datalog queries in our editor. I'd also love for logseq to be using standard datascript so we can start to explore using datascript via bb. Thanks for this library as it has done wonders for logseq! Cheers
=> Add get to built-ins for binding on map values

src/datascript/core.cljc, src/datascript/db.cljc, src/datascript/impl/entity.cljc, test/datascript/test/entity.cljc, test/datascript/test/lookup_refs.cljc, test/js/tests.js
Ref: https://github.com/tonsky/datascript/issues/447
I'm not sure about the fastest way to check that an entity exists in the database.
I used `(empty? (db/-search db [e]))` here, but presumably there's some allocation overhead from creating an iterator.
Perhaps there's a cheaper way to do it (maybe seeking on the index directly and checking for an eid match?)
I'm open to suggestions and am happy to take a second look later with profiling if desired.
=> Entity should return nil for numeric eids that don't correspond to entities

bench/datascript/bench/datascript.cljc, src/datascript/query.cljc
The `-collect` fn, run at the end of a query, correctly shortcircuits with the following comment: `"one empty rel means final set has to be empty"`
However, while processing the query clauses, there was no shortcircuit. Because the implementation of `lookup-pattern` is agnostic to existing rels, this means that the query engine will continue slicing the indexes for every tuple that could possibly match every clause until all clauses are exhausted.
This is a one-line change to add a shortcircuit in `resolve-clause` if any existing relation is empty. The check is cheap, and it should provide a substantial performance boost in many common cases.
Motivation: substantial performance boost for a real-world app
=> Query: shortcircuit query when result is guaranteed to be empty

src/datascript/query.cljc, test/datascript/test/query_or.cljc
[My previous PR](https://github.com/tonsky/datascript/pull/459) inadvertently broke or/or-join when a branch shortcircuits due to being empty. (Sorry!)
If one branch of an `or` or `or-join` short-circuited, the resulting Relation would not have the expected attrs, resulting in `Can’t sum relations with different attrs` being raised.
This fixes the bug and adds regression tests. Fixing that also exposed an extant bug in `same-keys?` which is now fixed.
=> Bugfixes for sum-rel and shortcircuited or/or-join branches

src/datascript/db.cljc, test/datascript/test/transact.cljc
Potential fix for #474, not sure if ideal.
=> Fix :db.fn/call returning entity without :db/id

docs/queries.md
datomic docs seem to be shuffled around nowadays.
=> Fix the link to datomic docs
